---
driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536

suites:
- name: default
  run_list: ["recipe[et_search_api]"]
  attributes: {}
