---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret

platforms:
- name: ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[et_search_api]
